site_name: "BCH EARL Documents"
site_url: https://mengxiangxi.info/BCHEARL-Docs
repo_url: https://github.com/MengXiangxi/BCHEARL-Docs/
edit_uri: edit/main/docs

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
      - yaml
      - rust

extra:
  analytics:
    provider: google
    property: G-SZB618VNBZ

plugins:
  - search
  - awesome-pages

extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.smartsymbols
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  - smarty
  - fontawesome_markdown
  - pymdownx.arithmatex:
        generic: true